### ISSUE TITLE
Peer dependencies seem to be rendered only for root packages

### ISSUE THREAD

**Issue by stof** [npmgraph/npmgraph#104]
While `devDependencies` is indeed a root-only concept, `peerDependencies` is not (the peer dependencies of your dependencies must be satisfied). So to me, the peer dependencies deeper in the tree should be rendered as links too (the dependency resolution should make them link to the package depended on by the parent)

**Comment by broofa** [comment]
> they should not be ghosted, as they are normal dependencies

I disagree.  If I do `npm install autoprefixer`, I don't get the peer dependencies.  It is incumbent upon me to explicitly add them. I have to explicitely type `npm install postcss` so that `postcss` is added to my normal `dependencies` list.  If I do that then, sure, we should show `postcss` as a normal module (but probably still shade the dependency line to it).

But if I haven't explicitly installed `postcss`, then neither it nor any of it's sub-dependencies will exist, and we shouldn't indicate anything to the contrary.

**Comment by stof** [comment]
@broofa I mean that they should not  be ghosted *when we link to the dependency provided by the parent*, as `postcss` is not a ghost in the tree then.
However, the link itself should still have a style indicating a peer dependency (dashed linked in your proposal, green link in the existing code)
