### ISSUE TITLE
Linkify maintainers

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#294]
It seems that they're active, but nothing happens. Is this a bug? What's `Selectable`?

![scroll](https://github.com/user-attachments/assets/500db525-0ba8-4fbe-b883-eed50e4f1e60)

If not, linkifying them would be as easy as wrapping this in a `<a>`

https://github.com/npmgraph/npmgraph/blob/ae30749216326d248c29ccba220c6d070f16e489/components/GraphPane/reports/reporters/maintainersAll.tsx/#L16-L25

**Comment by broofa** [comment]
Clicking a maintainer selects all modules associated with that maintainer.
The problem is that for maintainers listed in **Module** tab, if a maintainer is only associated with that module and none others, it's a no-op.  (Just selects the already-selected module.)

It does do something if a maintainer has other modules, however...

https://github.com/user-attachments/assets/6871fd3c-200a-411e-b463-0b4ffb3a5471

... but that brings up another issue, which is that particular use case isn't great either since (as shown) it just clears out the modules tab ("multiple modules selected").  Previously it would have switched to the **Graph** tab automatically, which was a bit more interesting, but we don't do that anymore ... 🤷

**Comment by fregante** [comment]
> Clicking a maintainer selects all modules associated with that maintainer.

Oh that makes sense, this behavior is indeed everywhere on the Graph tab but in Module it's only for maintainers.







> it's a no-op. (Just selects the already-selected module.)

Yeah, it's a similar issue when re-loading certain packages:

- https://github.com/npmgraph/npmgraph/issues/283

Maybe it can be resolved via small notifications, like "3 packages by xyz selected"



> Previously it would have switched to the **Graph** tab automatically

It doesn't look like it: ([April 2024](https://npmgraph-git-fork-xhmikosr-patch-1-npmgraph.vercel.app/?q=browserify#select=exact%3Apublic-encrypt%404.0.3))

![scroll](https://github.com/user-attachments/assets/8358d860-56db-44ef-9e13-2aa33e60ff4a)



> but we don't do that anymore

In some cases we can do that, I was mostly annoyed at the auto-switch on `enter` and background click.
