### ISSUE TITLE
Use `parcel` for building?

### ISSUE THREAD

**Issue by broofa** [npmgraph/npmgraph#60]
@fregante Thoughts on using `parcel` for code packaging?  I've had good experiences with it, and will allow us to use actual React + JSX syntax instead of the kludgy notation currently needed for `htm`+`preact`.

FWIW, I've started porting the codebase over on my local box just to see how it feels and I'm inclined to keep going with it unless you have strong opinions to the contrary.

**Comment by fregante** [comment]
I’m not against it, certainly it would enable using dependencies more effectively. 

As for the box comment, are you saying you want to keep the deployment towards your hosting? That’s ok as long as it’s still automated via GitHub Actions. You could also set up Vercel to make it easier (and give us automatic PR preview URLs)

**Comment by broofa** [comment]
> As for the box comment are you saying you want to keep the deployment towards your hosting?

No, not at all.  I was just referring to the the local repo branch I was working on, that I've now pushed as [draft] PR, #61.  You're welcome to take a look, but it's not ready for review just yet.

As for deployment, I haven't thought that through yet. We'll need to run `parcel build` and make sure Github serves the "Pages" from the resulting directory of static assets (/dist?).  'Not really sure what the best way to do that will be.

**Comment by broofa** [comment]
BTW, I see you're part of the Rollup org.  I don't have much experience with Rollup, but I'm not wedded to Parcel.   I went with it because I've been using it on another side-project and it's been working pretty well.  The only real requirements here are the ability to work with ESM modules and React+JSX.  Other than that... whatever works.

**Comment by fregante** [comment]
Ah I got it now.

> As for deployment

We have 2 choices:

- use GitHub Pages on `main` and have it force-push to `gh-pages`, copying: https://github.com/fregante/github-url-detection/blob/master/.github/workflows/demo.yml
- customizing the native GitHub Pages build to include parcel in its process

The first one is easy because I already solved it and it's a matter of copy-pasting and adjusting that workflow.

The second one frees us from dealing with a workflow and `gh-pages` branch since GitHub Pages would take care of it, but I haven't found a way to achieve it, there's only a [plugin for browserify](https://github.com/kui/jekyll-browserify)

> I'm not wedded to Parcel

Me neither, I just use whatever tool is easiest. Rollup requires a lot of config so I generally go with Parcel for apps like this.
