### ISSUE TITLE
Defer loading of wasm file

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#64]
If you use the `import()` function the website will be usable earlier (e.g. it can start resolving the graph) _while_ it downloads this huge dependency.

```
docs/graphvizlib.d416b260.wasm      ⚠️  1 MB
docs/index.80c6c8bb.js                  368.92 KB   
```

**Comment by broofa** [comment]
Good point.

FWIW, this was the most problematic part of switching to Parcel.  I ended up removing `d3-graphviz` because it relied on `@hpcc/wasm`'s default behavior for loading the WASM file, which wasn't working with parcel bundling.  Not a big surprise that, I suppose.  Switching to `import()` shouldn't be a big deal as long as parcel groks what's going on there.
