### ISSUE TITLE
Error: Bugsnag failed to load. Maybe disable your ad blocker for this site?

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#69]
<img width="527" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/115427308-901c4f80-a22b-11eb-9026-0fe172ad01d6.png">

I see this all the time. It's not a message the user should see

**Comment by broofa** [comment]
Is the problem that the message is inaccurate (e.g. do you not have an ad blocker?), or is it that showing this to the user isn't appropriate?

FWIW, my rationale for surfacing this issue is that users are currently [told they don't need to report issues](https://github.com/npmgraph/npmgraph/blob/main/index.html#L82-L89) because they're reported automatically.  If bugsnag isn't loading, that stops being true, so any errors they see will probably go unreported.

**Comment by fregante** [comment]
> that showing this to the user isn't appropriate

I don't know what bugsnap is or why it should be enabled. It doesn't affect me as a user until there's actually a bug. I'd rather show this message on that page:

- bugsnap on: "It's been reported and we should have it fixed soon"
- bugsnap off: "The automated bug reported was blocked by your browser. Open an issue?"
