### ISSUE TITLE
Accept `package.json` via parameter

### ISSUE THREAD

**Issue by fregante** [npmgraph/npmgraph#94]
npmgraph lets the user upload package.json files via UI but there's no way to share them. A `packagejson` parameter would also let anyone just pass the whole file.

**Comment by broofa** [comment]
Good idea.  Misc. thoughts ...

We'll need to account for [limits on URL lengths](https://stackoverflow.com/a/417184/109538) at some point.  Maybe strip out whitespace and non-essential fields?

This would help fix another long-standing issue, which is that reloading the page breaks when viewing an uploaded package, due to the file contents only being stored in memory.

I think there's a related use case, which is the ability to reference a package.json by URL (npmgraph `fetch()`s the content for you).  So the URL would look something like https://npmgraph.js.org?packageURL=https%3A%2F%2Fraw.githubusercontent.com%2Fnpmgraph%2Fnpmgraph%2Fmain%2Fpackage.json`.   (Hmm... and it looks like this can work for private repos as well.  If you go to the "Raw" view of a package.json file, you get a URL that has an access `token` param, that appears to grant access to anyone with that URL.  Meaning users could share dependency graphs for private repos with anyone.  I'm not sure that's a good thing, but I don't know that that's our problem.)

**Comment by fregante** [comment]
> ability to reference a package.json by URL

Oh I didn't realize that GitHub allowed CORS 🤔 it looks like it's possible without having to proxy the request.


> which is that reloading the page breaks when viewing an uploaded package, due to the file contents only being stored in memory.

We can totally store them in localStorage too, as long as we limit it to the last 5-10

**Comment by fabiospampinato** [comment]
> We'll need to account for [limits on URL lengths](https://stackoverflow.com/a/417184/109538) at some point. Maybe strip out whitespace and non-essential fields?

If the package is embedded in the fragment portion of the URL I think the limit Chrome has for that is around 2MB, which would be plenty.

**Comment by broofa** [comment]
> Also fragments are not sent to the server

Excellent point.

I do wonder a bit about the viability of sharing such large URLS.  Even a modest-size package.json file is going to be 1K+ chars when URI-encoded.  Something about this feels a bit messy messy to me.    It makes doing *anything* in the location field really error prone for users.

I find myself thinking that if/when we add support for something like this, the browser should grab the content of the package out of the URL, treat it just like a file-upload, and then immediately `replaceState()` so the URL isn't so cumbersome.

And, similarly, we could provide a "copy shareable link" button in the Recent Uploads section of the Info pane.

----

FWIW, once #156 lands users should be able to paste the contents of package.json files in GH gists, and use the "Raw" url to generate graphs.   For example,  https://npmgraph-git-uploadurl-npmgraph.vercel.app/?q=https%3A%2F%2Fgist.githubusercontent.com%2Fbroofa%2F1ade3ba810f8149039a7f53bba7cc6ac%2Fraw%2F56c40290dd7fd2ead5b7ed59f0151a9dcccd036f%2Fgistfile1.txt

**Comment by fabiospampinato** [comment]
> the browser should grab the content of the package out of the URL, treat it just like a file-upload

That doesn't work for private packages though. For example I fairly often check the graph for the package.json of the app I work on, if I can embed the file in the url then that works for me for anything basically, private packages, unpublished ones, public ones, anything. If it only works for public urls though then my use case is immediately not covered. 

I think embedding the package in a fragment is worth supporting, because it takes like 3 lines of code to decode it, no network requests, it's not bad I think.

**Comment by broofa** [comment]
see https://github.com/npmgraph/npmgraph/pull/157

**Comment by broofa** [comment]
This is now supported.  I've updated the README with documentation about the URL API.

**Comment by fregante** [comment]
> We'll need to account for [limits on URL lengths](https://stackoverflow.com/a/417184/109538)

https://twitter.com/JLarky/status/1771603877676142666
